network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s25:
      addresses:
        - 140.113.200.162/26
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
      routes: 
        - to: default
          via: 140.113.200.190
